In [1]:
import numpy as np

1.Create a vector with values ranging from 10 to 49.

In [ ]:
import numpy as np

vector = np.arange(10, 50)
vector

2.Create a 3x3 matrix with values ranging from 0 to 8.

In [ ]:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n2. 3x3 matrix with values 0 to 8:\n", matrix_3x3)

Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.

In [2]:
A_system = np.random.random((3, 3))
b_system = np.random.random((3, 1))
x_solution = np.linalg.solve(A_system, b_system)

Compute the matrix-vector product.

In [3]:
matrix_5x5_sum = np.random.random((5, 5))
row_sums = matrix_5x5_sum.sum(axis=1)
column_sums = matrix_5x5_sum.sum(axis=0)

Create a 3x3 random matrix and a 3-element column vector. 

In [4]:
matrix_3x3_vec = np.random.random((3, 3))
vector_3x1 = np.random.random((3, 1))
matrix_vector_product = np.dot(matrix_3x3_vec, vector_3x1)

Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

In [5]:
matrix_A_3x4 = np.random.random((3, 4))
matrix_B_4x3 = np.random.random((4, 3))
matrix_product_A_B = np.dot(matrix_A_3x4, matrix_B_4x3)

Create a 3x3 matrix and calculate its determinant.


In [6]:
matrix_3x3_det = np.random.random((3, 3))
determinant = np.linalg.det(matrix_3x3_det)


Given a 4x4 matrix, find its transpose.

In [7]:
matrix_4x4 = np.random.random((4, 4))
transpose_4x4 = matrix_4x4.T



Create two 3x3 matrices and compute their dot product.

In [8]:
matrix_A = np.random.random((3, 3))
matrix_B = np.random.random((3, 3))
dot_product_3x3 = np.dot(matrix_A, matrix_B)

Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [9]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
matrix_product_5x3_3x2 = np.dot(matrix_5x3, matrix_3x2)

Normalize a 5x5 random matrix.

In [10]:
matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (matrix_5x5 - matrix_5x5.min()) / (matrix_5x5.max() - matrix_5x5.min())

Create a random vector of size 30 and find the mean value.

In [11]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()

Create a 10x10 array with random values and find the minimum and maximum values.

In [12]:
array_10x10 = np.random.random((10, 10))
min_value = array_10x10.min()
max_value = array_10x10.max()

Create a 3x3x3 array with random values.

In [13]:
random_3x3x3 = np.random.random((3, 3, 3))
print("\n4. 3x3x3 array with random values is \n")


4. 3x3x3 array with random values is 



Create a 3x3 identity matrix.

In [14]:
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)


3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
